services:

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: 3306
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - app-network

  telegram-bot:
    build:
      context: ./bot  # Указываем каталог с ботом
    environment:
      # bot env data
      BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      # DB env data
      MYSQL_DATABASE: legality
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./bot:/app  # Примонтировать папку bot внутрь контейнера
    restart: always
    command: python /app/main.py
    depends_on:
      - db
    ports:
      - "8081:8080"  # Проброс порта для доступа (если нужен)
    networks:
      - app-network


  redis:
    image: "redis:latest"
    container_name: "my-redis-container"
    ports:
      - "6379:6379"
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: legality
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:

