version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-a
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: legality
    ports:
      - "3306:3306"  # Проброс портов для доступа к MySQL с хост-машины
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest  # Образ Adminer для администрирования MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8081:81"  # Проброс порта для доступа к Adminer с хост-машины

  telegram-bot:
    build:
      context: .  # Контекст сборки - текущий каталог, где находится Dockerfile
    environment:
      BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      GIT_AUTH_TOKEN: ${GIT_AUTH_TOKEN}
      TOKEN_ADMIN: ${TOKEN_ADMIN}
    volumes:
      - .:/app  # Примонтировать текущий каталог (с Dockerfile) внутрь контейнера в /app
    restart: always  # Всегда перезапускать контейнер
    command: python /app/head_bot/main.py  # Команда для запуска вашего бота
    secrets:
      - git_ssh_key
    depends_on:
      - db

  git-updater:
    image: alpine/git
    volumes:
      - .:/app
    command: >
      sh -c "while :;
      do
        git -C /repo pull;
        sleep 7200;
      done"
    secrets:
      - git_ssh_key

secrets:
  git_ssh_key:
    file: .env