version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty654321
      MYSQL_DATABASE: legality
      MYSQL_USER: root
      MYSQL_PASSWORD: Zxxcvbnm,./
    ports:
      - "3306:3306"  # Проброс портов для доступа к MySQL с хост-машины
    volumes:
      - ./mysql-data:/var/lib/mysql

  adminer:
    image: phpmyadmin:latest  # Образ Adminer для администрирования MySQL
    restart: always
    ports:
      - "8080:8080"  # Проброс порта для доступа к Adminer с хост-машины
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql

  telegram-bot:
    build:
      context: .  # Контекст сборки - текущий каталог, где находится Dockerfile
    environment:
      BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      GIT_AUTH_TOKEN: ${GIT_AUTH_TOKEN}
      TOKEN_ADMIN: ${TOKEN_ADMIN}
    volumes:
      - .:/app  # Примонтировать текущий каталог (с Dockerfile) внутрь контейнера в /app
    restart: always  # Всегда перезапускать контейнер
    command: python /app/head_bot/main.py  # Команда для запуска вашего бота
    secrets:
      - git_ssh_key
    depends_on:
      - mysql

  git-updater:
    image: alpine/git
    volumes:
      - .:/app
    command: >
      sh -c "while :;
      do
        git -C /repo pull;
        sleep 7200;
      done"
    secrets:
      - git_ssh_key

secrets:
  git_ssh_key:
    file: .env