version: '3.1'

services:
  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "8081:80"
    environment:
      SA_PASSWORD: "change_this_password"
      ACCEPT_EULA: "Y"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1